const SET_CATEGORIES = 'SET_CATEGORIES';
const SET_STATIONS = 'SET_STATIONS';
const SET_STATES = 'SET_STATES';
const SET_DATASETS = 'SET_DATASETS';
const SET_DATA = 'SET_DATA';

export {
    SET_CATEGORIES,
    SET_STATIONS,
    SET_STATES,
    SET_DATASETS,
    SET_DATA,
}